spring:
  security:
    user:
      password: password
  ssl:
    bundle:
      pem:
        localhost:
          keystore:
            certificate: "classpath:localhost.example.pem"
            private-key: "classpath:localhost.example-key.pem"
server:
  port: 8443
  ssl:
    bundle: localhost
#    key-store: "classpath:localhost-key.pem"
#    key-store-password: "password"
#    key-password: "password"